#!/bin/bash

set -euo pipefail

if [[ $EUID -ne 0 ]]; then
    exec pkexec --disable-internal-agent "$0" "$@"
fi

ACTION="${1:-}"

function Log() {
    printf "%s\n" "$*"
    printf "%s\n" "$*" | logger -t io-priv-exec -p user.warning
}

case "$ACTION" in
    fan-control-on)
        Log "fan-control-on"
        sv up jupiter-fan-control
        ;;
    fan-control-off)
        Log "fan-control-off"
        sv down jupiter-fan-control
        ;;
    wifi-powersave-on)
        Log "wifi-powersave-on"
        iw dev wlo1 set power_save on
        ;;
    wifi-powersave-off)
        Log "wifi-powersave-off"
        iw dev wlo1 set power_save off
        ;;
    *)
        Log "decline: unknown action $ACTION"
        exit 1
        ;;
esac